name = "strategi-chat"
main = "src/index.js"
compatibility_date = "2024-09-23"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "strategiskskole-ai"
database_id = "e3b67a7b-5dfd-4be2-8a36-6c0ecf770fdc"

[vars]
ALLOWED_ORIGINS = "https://strategiskskole.dk,https://www.strategiskskole.dk"
