// ── FARVER ────────────────────────────────────────────────
export const C = {
  navy: "#1A3A5C",
  blue: "#2E6DA4",
  light: "#D5E8F0",
  gold: "#C8A84B",
  gray: "#5A5A5A",
  bg: "#f7f9fb",
  warm: "#f4ede4",
};

// ── TRIN-SEKVENS: Åbning → 6×(Model + Humant) → Afslutning = 14 trin ──
export const STEPS = [
  { id: "aabning", nr: 0, type: "aabning", navn: "Åbning", label: "Åbning", farve: C.blue, spørgsmål: "Hvad bringer du med ind i rummet?", kontekst: "Inden vi begynder — hvad fylder, og hvad håber du at få ud af dette?" },
  { id: "t1-model", nr: 1, type: "model", navn: "Spejling", label: "1. Spejling", farve: C.blue, spørgsmål: "Hvad er det vi egentlig står i?", kontekst: "Se virkeligheden klart — ikke som vi ønsker den." },
  { id: "t1-human", nr: 1, type: "human", navn: "Usikkerhed", label: "Usikkerhed", farve: C.gold, spørgsmål: "Hvad bærer du med dig — som du ikke siger højt?", kontekst: "Det menneskelige rum — her er plads til det der fylder." },
  { id: "t2-model", nr: 2, type: "model", navn: "Klarhed", label: "2. Klarhed", farve: C.blue, spørgsmål: "Hvad er problemet bag problemet?", kontekst: "Find den egentlige diagnose bag symptomerne." },
  { id: "t2-human", nr: 2, type: "human", navn: "Sårbarhed", label: "Sårbarhed", farve: C.gold, spørgsmål: "Hvad koster det at se klart?", kontekst: "Det menneskelige rum — ærlighed kræver sårbarhed." },
  { id: "t3-model", nr: 3, type: "model", navn: "Valg", label: "3. Valg", farve: C.blue, spørgsmål: "Hvad vælger vi — og hvad vælger vi fra?", kontekst: "At sige ja er kun meningsfuldt, hvis vi også siger nej." },
  { id: "t3-human", nr: 3, type: "human", navn: "Mod", label: "Mod", farve: C.gold, spørgsmål: "Hvad koster det at vælge — og hvad koster det ikke at gøre det?", kontekst: "Det menneskelige rum — modige valg kræver noget af os." },
  { id: "t4-model", nr: 4, type: "model", navn: "Struktur", label: "4. Struktur", farve: C.blue, spørgsmål: "Hvordan organiserer vi os?", kontekst: "Design de rammer der gør strategien mulig." },
  { id: "t4-human", nr: 4, type: "human", navn: "Tillid", label: "Tillid", farve: C.gold, spørgsmål: "Hvad bygger vi rammerne på — kontrol eller tillid?", kontekst: "Det menneskelige rum — rammer fortæller noget om relationer." },
  { id: "t5-model", nr: 5, type: "model", navn: "Kernen", label: "5. Kernen", farve: C.blue, spørgsmål: "Kan vi se det i praksis tirsdag kl. 10?", kontekst: "Prøven: kan strategien mærkes i hverdagen?" },
  { id: "t5-human", nr: 5, type: "human", navn: "Ærlighed", label: "Ærlighed", farve: C.gold, spørgsmål: "Hvad ser vi — som vi ikke taler om?", kontekst: "Det menneskelige rum — sandheden kræver mod." },
  { id: "t6-model", nr: 6, type: "model", navn: "Forankring", label: "6. Forankring", farve: C.blue, spørgsmål: "Hvordan holder vi det levende?", kontekst: "Strategier dør ikke af modstand — de dør af glemsel." },
  { id: "t6-human", nr: 6, type: "human", navn: "Udholdenhed", label: "Udholdenhed", farve: C.gold, spørgsmål: "Hvad kræver det at holde fast — når hverdagen vender tilbage?", kontekst: "Det menneskelige rum — forandring kræver udholdenhed." },
  { id: "afslutning", nr: 7, type: "afslutning", navn: "Afslutning", label: "Afslutning", farve: C.navy, spørgsmål: "Hvad tager vi med herfra — og hvad gør vi i morgen?", kontekst: "Vi samler op: erkendelser, beslutninger og konkrete næste skridt." },
];

export const ROLLER = [
  { key: "skoleleder", label: "Skoleleder", icon: "🏫", desc: "Arbejd med din personlige ledelsesopgave" },
  { key: "ledelsesteam", label: "Ledelsesteam", icon: "👥", desc: "Styrk jeres fælles retning og klarhed" },
  { key: "bestyrelse", label: "Bestyrelse", icon: "🏛️", desc: "Skærp bestyrelsens strategiske rolle" },
];

// ── PROCESKORT DATA ───────────────────────────────────────
export const AABNING = {
  forside: "Før vi begynder — hvad bringer I med ind i rummet?",
  aabning: ["Hvad fylder hos jer lige nu?", "Hvad håber I at gå herfra med?", "Hvad er den vigtigste ting, I har brug for at blive klogere på i dag?"],
  ramme: ["Vi arbejder med virkelige situationer — ikke cases", "Der er ingen rigtige svar — men der er skarpere spørgsmål", "Vi arbejder os gennem modellens trin — ét ad gangen", "Hvert trin har et output, der fører videre til det næste"],
  erkendelse: "Et fælles afsæt: hvad er vi her for, og hvad vil vi arbejde med?",
};

export const AFSLUTNING = {
  forside: "Hvad tager vi med herfra — og hvad gør vi i morgen?",
  aabning: ["Hvad er den vigtigste erkendelse fra i dag?", "Hvad har vi besluttet — og hvem gør hvad?", "Hvad var overraskende — eller svært?", "Hvad har vi brug for at vende tilbage til?"],
  ramme: ["Hvert trin har givet et konkret output", "Handlingerne starter i morgen — ikke 'snart'", "Vi mødes igen tirsdag kl. 10 — med status på det vi aftalte"],
  erkendelse: "Vi ved, hvad vi gør — og vi ved, hvem der gør hvad.",
};

export const MODEL_KORT = {
  skoleleder: [
    { forside: "Hvad er det, jeg faktisk står i som skoleleder?", aabning: ["Hvad er det for en situation, jeg står i lige nu?", "Hvad kalder tydeligt på min opmærksomhed?", "Hvor mister jeg retning eller overblik?"], skaerpelse: ["Hvad gør jeg i dag — som ikke skaber retning?", "Hvornår bliver jeg uklar i min ledelse?", "Hvad undgår jeg at tage fat på?"], perspektiv: ["Hvad kalder situationen på af ledelse?", "Hvad er min opgave — og hvad er ikke min?", "Hvad gør jeg anderledes fra i morgen?"], erkendelse: "Et klart billede af situationen og skolelederens opgave." },
    { forside: "Hvad er det egentlige problem — ikke symptomet?", aabning: ["Hvad holder mig faktisk tilbage?", "Hvad forsøger jeg at løse — igen og igen?", "Hvad binder problemerne sammen?"], skaerpelse: ["Hvad er symptomet — og hvad er problemet bag?", "Hvad ville klarhed gøre muligt?", "Hvad undgår jeg at sige højt?"], perspektiv: ["Hvad kræver det at finde egentlig klarhed?", "Hvad kan ingen se tydeligere end jeg?", "Hvad ville ændre sig, hvis jeg var klar?"], erkendelse: "En præcis formulering af det egentlige problem." },
    { forside: "Hvad er mit ledelsesmæssige valg?", aabning: ["Hvad er de reelle muligheder?", "Hvad trækker mig i forskellige retninger?", "Hvad viger jeg uden om?"], skaerpelse: ["Hvad siger jeg ja til — med min tid?", "Hvad er jeg nødt til at sige nej til?", "Hvad koster det ikke at vælge?"], perspektiv: ["Hvad kræver valget af mig som leder?", "Hvad er konsekvensen for teamet?", "Hvad ville jeg fortryde?"], erkendelse: "Et tydeligt og ansvarligt ledelsesvalg." },
    { forside: "Har jeg designet de rigtige rammer?", aabning: ["Hvad er den nuværende struktur til for?", "Hvad fungerer — og hvad ikke?", "Hvem er strukturen designet for?"], skaerpelse: ["Hvilke møder skaber retning — og hvilke er vane?", "Hvad er for meget — og hvad mangler?", "Hvad ville jeg ændre fra scratch?"], perspektiv: ["Hvad kalder strukturen på af ledelse?", "Hvad skal designes — og hvad frigives?", "Hvad ændrer jeg først?"], erkendelse: "En klar forståelse af, hvad der skal redesignes." },
    { forside: "Er strategien til stede tirsdag kl. 10?", aabning: ["Hvad sker der faktisk i vores møder?", "Hvad siger dagsordenen om prioriteringerne?", "Hvad siger stemningen om kulturen?"], skaerpelse: ["Hvad beslutter vi — og hvad udskydes?", "Hvad er alle enige om at undgå?", "Hvornår mærkes strategien?"], perspektiv: ["Hvad kalder det på af ledelse?", "Hvad er mit ansvar?", "Hvad gør jeg anderledes næste tirsdag?"], erkendelse: "Et ærligt billede af, om strategien lever." },
    { forside: "Hvad gør jeg, for at det holder?", aabning: ["Hvad er mit ansvar for at holde strategien levende?", "Hvad gør jeg allerede — og hvad har jeg glemt?", "Hvad er tegnet på, at det holder?"], skaerpelse: ["Hvad dør stille — fordi ingen holder fast?", "Hvornår tjekker jeg op — og hvornår ikke?", "Hvad er der kun brug for, at jeg gør?"], perspektiv: ["Hvad er min forankringsrolle?", "Hvad er tegnet på, at strategien lever?", "Hvad gør jeg konkret for at holde det levende?"], erkendelse: "Et forpligtende billede af min forankringsrolle." },
  ],
  ledelsesteam: [
    { forside: "Hvad er det, vi faktisk står i sammen?", aabning: ["Hvad er situationen, vi befinder os i fælles?", "Hvornår håndterer vi situationer forskelligt?", "Hvornår overlader vi noget uden aftale?"], skaerpelse: ["Hvad gør vi, som ikke skaber klarhed?", "Hvad undgår vi at tale om?", "Hvornår er vi for enige — eller for utydelige?"], perspektiv: ["Hvad kalder situationen på af fælles ledelse?", "Hvad er vores fælles opgave?", "Hvad gør vi anderledes fra næste uge?"], erkendelse: "Et klart billede af teamets fælles opgave." },
    { forside: "Hvad er det, vi ikke får talt om?", aabning: ["Hvilke mønstre ser vi gentage sig?", "Hvad ligger bag uroen hos medarbejderne?", "Hvad ser vi, som vi ikke har delt?"], skaerpelse: ["Hvornår nøjes vi med at håndtere?", "Hvilken samtale har vi undgået?", "Hvad ved vi — men har ikke gjort fælles?"], perspektiv: ["Hvad er den fælles opgave, der viser sig?", "Hvad kræver det at handle?", "Hvad er den første fælles handling?"], erkendelse: "En fælles erkendelse af den egentlige opgave." },
    { forside: "Hvad prioriterer vi — og hvad holder vi op med?", aabning: ["Hvad er vores fælles topprioritet?", "Hvad ville vi stoppe, hvis vi turde?", "Hvad gør vi, fordi det forventes?"], skaerpelse: ["Hvornår lader vi alle køre deres eget?", "Hvad sker der, når vi ikke er enige?", "Hvad undgår vi at vælge fra?"], perspektiv: ["Hvad ville medarbejderne mærke?", "Hvad kræver det at stå sammen?", "Hvad kommunikerer vi — og hvornår?"], erkendelse: "En fælles prioritering, der styrker det hele." },
    { forside: "Hvordan organiserer vi os for det valgte?", aabning: ["Hvordan fordeler vi ansvaret?", "Hvilke rutiner understøtter retningen?", "Hvad skal ledelsesmøderne handle om?"], skaerpelse: ["Hvornår arbejder vi i hinandens felter?", "Hvilken rutine ville vi droppe?", "Hvad sker der, når organiseringen ikke matcher?"], perspektiv: ["Hvad ville medarbejderne mærke?", "Hvilken aftale laver vi om roller?", "Hvad ændrer I fælles først?"], erkendelse: "Klare roller og mønstre for opfølgning." },
    { forside: "Kan vi se vores fælles retning i hverdagen?", aabning: ["Kan man se, at vi har en fælles retning?", "Hvad ville vi opdage tirsdag kl. 10?", "Hvad fortæller medarbejdernes spørgsmål?"], skaerpelse: ["Hvornår er planen kun fælles i ledelsesmøderne?", "Hvad gør vi forskelligt, som forvirrer?", "Hvornår dækker vi over uklarhed?"], perspektiv: ["Hvad ville medarbejderne mærke?", "Hvad gør vi anderledes fra i morgen?", "Hvor justerer vi først?"], erkendelse: "Strategi der lever i hverdagen." },
    { forside: "Hvordan sikrer vi, at beslutningerne lever?", aabning: ["Hvad gør vi i næste uge for at følge op?", "Hvordan holder vi hinanden fast?", "Hvordan kommunikerer vi beslutningerne?"], skaerpelse: ["Hvornår har vi besluttet noget, der døde stille?", "Hvad sker der, når én falder tilbage?", "Hvad er vores største risiko?"], perspektiv: ["Hvad mærker medarbejderne om en måned?", "Hvornår mødes vi næste gang?", "Hvad aftaler vi konkret?"], erkendelse: "Konkrete aftaler og fælles ansvar." },
  ],
  bestyrelse: [
    { forside: "Hvad er det, vi faktisk står i som bestyrelse?", aabning: ["Hvad hører vi fra forældre og omverden?", "Hvornår er vi usikre på vores rolle?", "Hvad er vi i tvivl om ift. ledelsen?"], skaerpelse: ["Hvad gør vi, som skaber uklarhed?", "Hvad reagerer vi på i stedet for at sætte retning?", "Hvornår er vi for detaljerede eller for passive?"], perspektiv: ["Hvad kalder situationen på?", "Hvad er vores opgave — og hvad er det ikke?", "Hvad tager vi med herfra?"], erkendelse: "Et klart billede af bestyrelsens opgave." },
    { forside: "Hvad ser vi ikke — som vi burde se?", aabning: ["Hvad fortæller tallene os egentlig?", "Hvad ved vi for lidt om?", "Hvad ville vi opdage bag referaterne?"], skaerpelse: ["Hvornår accepterer vi for glatte svar?", "Hvad spørger vi aldrig om?", "Hvornår er vi for langt fra virkeligheden?"], perspektiv: ["Hvad er bestyrelsens opgave her?", "Hvad kræver det at spørge ind uden at overtage?", "Hvad spørger vi ledelsen om?"], erkendelse: "En skarpere forståelse af skolens situation." },
    { forside: "Hvad beslutter vi — og hvad lader vi ligge?", aabning: ["Hvad er det vigtigste, bestyrelsen kan beslutte?", "Hvad beder vi ledelsen om, som modarbejder fokus?", "Hvad ville vi sige nej til?"], skaerpelse: ["Hvad hører til bestyrelsens bord?", "Hvornår drøfter vi i stedet for at beslutte?", "Hvad koster det, at vi ikke vælger?"], perspektiv: ["Hvad ville ledelsen mærke?", "Hvad kræver valget af os?", "Hvad kommunikerer vi?"], erkendelse: "En tydelig bestyrelsesprioritering." },
    { forside: "Har vi en struktur der skaber værdi?", aabning: ["Hvad er vores møder til for?", "Hvad handler de om — og hvad burde de?", "Hvad savner vi i organiseringen?"], skaerpelse: ["Hvornår handler møderne om drift?", "Hvad er for meget — og hvad for lidt?", "Hvad ville vi ændre forfra?"], perspektiv: ["Hvad ville ledelsen mærke?", "Hvad ændrer vi i mødestrukturen?", "Hvad er den vigtigste ændring?"], erkendelse: "En bestyrelsesstruktur der skaber værdi." },
    { forside: "Kan vi mærke bestyrelsens aftryk?", aabning: ["Hvad ville vi se en tirsdag kl. 10?", "Hvad ved medarbejderne om vores prioriteringer?", "Hvornår satte bestyrelsen sidst aftryk?"], skaerpelse: ["Hvad sker der mellem møderne?", "Hvornår er vi kun en formalitet?", "Hvad ville medarbejderne sige?"], perspektiv: ["Hvad kan bestyrelsen gøre uden at overtage?", "Hvad er tegnet på, at vi gør forskel?", "Hvad gør vi fra næste møde?"], erkendelse: "Bestyrelsesarbejde der mærkes." },
    { forside: "Hvordan forankrer vi bestyrelsens arbejde?", aabning: ["Hvad er vores opfølgningsstruktur?", "Hvornår evaluerer vi os selv?", "Hvad gør vi, når nye medlemmer kommer?"], skaerpelse: ["Hvad dør stille, fordi ingen følger op?", "Hvad gør vi med gode intentioner?", "Hvornår bliver beslutninger til handling?"], perspektiv: ["Hvad er tegnet på en velfungerende bestyrelse?", "Hvad er vores vigtigste aftale?", "Hvem holder os fast?"], erkendelse: "En forpligtende forankring af bestyrelsens rolle." },
  ],
};

export const HUMAN_KORT = {
  skoleleder: [
    { label: "Usikkerhed", forside: "Hvad bærer du med dig — som du ikke siger højt?", aabning: ["Hvor føler du dig alene med ansvaret?", "Hvad er du usikker på — men lader som om du har styr på?", "Hvad ville du sige, hvis du turde?"], skaerpelse: ["Hvad koster det at bære usikkerheden alene?", "Hvornår bliver du en anden leder, end du vil være?", "Hvad sker der, når usikkerheden ikke bliver sagt?"], perspektiv: ["Hvad ville ændre sig, hvis usikkerheden fik plads?", "Hvad har du brug for fra dem du arbejder med?", "Hvad siger du højt her — som du ikke har sagt før?"], erkendelse: "Åbenhed om det der fylder — som grundlag for ærlig dialog." },
    { label: "Sårbarhed", forside: "Hvad koster det at se klart?", aabning: ["Hvornår er det lettere ikke at vide?", "Hvad risikerer du ved at sige det, du ser?", "Hvad sker der, når nogen siger noget ærligt?"], skaerpelse: ["Hvem betaler prisen, når vi ikke tør se klart?", "Hvornår bliver loyalitet en hindring for ærlighed?", "Hvad sker der, når vi undgår de rigtige spørgsmål?"], perspektiv: ["Hvad ville det betyde, hvis I turde se klart — sammen?", "Hvornår er sårbarhed en forudsætning for god ledelse?", "Hvad har I brug for af hinanden?"], erkendelse: "Tillid til at sige det, vi ser — også når det er svært." },
    { label: "Mod", forside: "Hvad koster det at vælge — og hvad koster det ikke at gøre det?", aabning: ["Hvem skuffer du, når du vælger tydeligt?", "Hvad er du bange for at tabe?", "Hvad ville du vælge med opbakning?"], skaerpelse: ["Hvem betaler prisen for din manglende beslutning?", "Hvornår er 'vi tager den til næste gang' et fravalg?", "Hvad sker der med respekten, når valget udebliver?"], perspektiv: ["Hvad gør modige valg ved et fællesskab?", "Hvad er det valg, du har udsat?", "Hvad har du brug for af de andre for at turde?"], erkendelse: "Erkendelse af hvad modet kræver — og hvad det giver." },
    { label: "Tillid", forside: "Hvad bygger vi rammerne på — kontrol eller tillid?", aabning: ["Hvornår skaber vi strukturer af tillid — og hvornår af mistillid?", "Hvad siger organiseringen om det, vi tror om hinanden?", "Hvad sker der, når rammerne er uklare?"], skaerpelse: ["Hvornår bruger vi struktur som skjold mod det menneskelige?", "Hvad sker der med relationer, når alt bliver processer?", "Hvornår er fravær af struktur fravær af omsorg?"], perspektiv: ["Hvad ville det betyde, hvis strukturerne var bygget på tillid?", "Hvornår har en god ramme givet frihed?", "Hvad har I brug for af hinanden?"], erkendelse: "Bevidsthed om hvad rammerne gør ved mennesker." },
    { label: "Ærlighed", forside: "Hvad ser vi — som vi ikke taler om?", aabning: ["Hvad ved alle — men ingen siger?", "Hvad ville vi se, hvis vi turde?", "Hvornår er der forskel på det, vi siger, og det vi gør?"], skaerpelse: ["Hvem betaler prisen, når vi ikke er ærlige?", "Hvad sker der med tilliden, når afstanden vokser?", "Hvornår er vi mere optagede af at beskytte os selv?"], perspektiv: ["Hvad ville ændre sig, hvis vi talte om det, vi ser?", "Hvad siger I til hinanden nu — som I ikke har sagt før?", "Hvad tager du ansvar for at sige?"], erkendelse: "Mod til at tale om virkeligheden." },
    { label: "Udholdenhed", forside: "Hvad kræver det at holde fast — når hverdagen vender tilbage?", aabning: ["Hvad er det sværeste ved at holde fast i forandring?", "Hvad har du brug for fra andre?", "Hvornår er det okay at tvivle?"], skaerpelse: ["Hvad sker der med mennesker, der hele tiden skal forandre sig?", "Hvornår presser vi mere på — i stedet for at anerkende?", "Hvad koster det, når vi ikke giver plads til træthed?"], perspektiv: ["Hvad giver dig energi til at fortsætte?", "Hvad tager du med herfra?", "Hvad gør du anderledes fra i morgen — for at passe på dig selv?"], erkendelse: "En realistisk erkendelse af hvad forandring kræver." },
  ],
  ledelsesteam: [
    { label: "Usikkerhed", forside: "Hvad bærer du med dig — som du ikke siger højt?", aabning: ["Hvor føler du dig alene med ansvaret?", "Hvad er du usikker på?", "Hvad ville du sige, hvis du turde?"], skaerpelse: ["Hvad koster det at bære usikkerheden alene?", "Hvornår bliver du en anden leder?", "Hvad sker der, når usikkerheden ikke siges?"], perspektiv: ["Hvad ville ændre sig, hvis usikkerheden fik plads?", "Hvad har du brug for?", "Hvad siger du højt her?"], erkendelse: "Åbenhed som grundlag for ærlig dialog." },
    { label: "Sårbarhed", forside: "Hvad koster det at se klart?", aabning: ["Hvornår er det lettere ikke at vide?", "Hvad risikerer du ved at sige det?", "Hvad sker der, når nogen er ærlig?"], skaerpelse: ["Hvem betaler prisen?", "Hvornår hindrer loyalitet ærlighed?", "Hvad sker der, når vi undgår spørgsmålene?"], perspektiv: ["Hvad ville det betyde, hvis I turde se klart?", "Hvornår er sårbarhed en forudsætning?", "Hvad har I brug for af hinanden?"], erkendelse: "Tillid til at sige det, vi ser." },
    { label: "Mod", forside: "Hvad koster det at vælge?", aabning: ["Hvem skuffer du?", "Hvad er du bange for at tabe?", "Hvad ville du vælge med opbakning?"], skaerpelse: ["Hvem betaler prisen?", "Hvornår er udsættelse et fravalg?", "Hvad sker der med respekten?"], perspektiv: ["Hvad gør modige valg?", "Hvad har du udsat?", "Hvad har du brug for?"], erkendelse: "Hvad modet kræver — og hvad det giver." },
    { label: "Tillid", forside: "Kontrol eller tillid?", aabning: ["Hvornår tillid — hvornår mistillid?", "Hvad siger organiseringen om hinanden?", "Hvad sker der med uklare rammer?"], skaerpelse: ["Hvornår er struktur et skjold?", "Hvad sker der, når alt er processer?", "Hvornår er fravær af struktur fravær af omsorg?"], perspektiv: ["Hvad ville tillidsbaserede strukturer betyde?", "Hvornår har rammer givet frihed?", "Hvad har I brug for?"], erkendelse: "Rammer bygget på tillid — ikke kontrol." },
    { label: "Ærlighed", forside: "Hvad ser vi — som vi ikke taler om?", aabning: ["Hvad ved alle?", "Hvad ville vi se?", "Hvornår er der forskel på ord og handling?"], skaerpelse: ["Hvem betaler prisen?", "Hvad sker der med tilliden?", "Hvornår beskytter vi os selv?"], perspektiv: ["Hvad ville ændre sig?", "Hvad siger I nu?", "Hvad tager du ansvar for?"], erkendelse: "Mod til at tale om virkeligheden." },
    { label: "Udholdenhed", forside: "Hvad kræver det at holde fast?", aabning: ["Hvad er det sværeste?", "Hvad har du brug for?", "Hvornår er det okay at tvivle?"], skaerpelse: ["Hvad sker der med mennesker i forandring?", "Hvornår presser vi mere?", "Hvad koster manglende plads til træthed?"], perspektiv: ["Hvad giver energi?", "Hvad tager du med?", "Hvad gør du for dig selv?"], erkendelse: "Hvad forandring kræver." },
  ],
  bestyrelse: [
    { label: "Det menneskelige rum", forside: "Hvad bærer du med dig — som du ikke siger højt?", aabning: ["Hvor føler du dig alene?", "Hvad er du usikker på?", "Hvad ville du sige?"], skaerpelse: ["Hvad koster usikkerheden?", "Hvornår bliver du en anden?", "Hvad sker der, når det ikke siges?"], perspektiv: ["Hvad ville ændre sig?", "Hvad har du brug for?", "Hvad siger du højt her?"], erkendelse: "Åbenhed som grundlag for dialog." },
    { label: "Det menneskelige rum", forside: "Hvad koster det at se klart?", aabning: ["Hvornår er det lettere ikke at vide?", "Hvad risikerer du?", "Hvad sker der med ærlighed?"], skaerpelse: ["Hvem betaler prisen?", "Hvornår hindrer loyalitet?", "Hvad sker der over tid?"], perspektiv: ["Hvad ville ærligt samarbejde betyde?", "Hvornår er sårbarhed nødvendig?", "Hvad har I brug for?"], erkendelse: "Tillid til at sige det, vi ser." },
    { label: "Det menneskelige rum", forside: "Hvad koster det at vælge?", aabning: ["Hvem skuffer du?", "Hvad er du bange for?", "Hvad ville du vælge?"], skaerpelse: ["Hvem betaler prisen?", "Hvornår er udsættelse fravalg?", "Hvad sker der med respekten?"], perspektiv: ["Hvad gør modige valg?", "Hvad har du udsat?", "Hvad har du brug for?"], erkendelse: "Hvad modet kræver." },
    { label: "Det menneskelige rum", forside: "Kontrol eller tillid?", aabning: ["Hvornår tillid — hvornår mistillid?", "Hvad siger organiseringen?", "Hvad med uklare rammer?"], skaerpelse: ["Hvornår er struktur et skjold?", "Hvad med relationer og processer?", "Hvornår er fravær af struktur fravær af omsorg?"], perspektiv: ["Hvad ville tillid betyde?", "Hvornår har rammer givet frihed?", "Hvad har I brug for?"], erkendelse: "Bevidsthed om rammer og mennesker." },
    { label: "Det menneskelige rum", forside: "Hvad ser vi — som vi ikke taler om?", aabning: ["Hvad ved alle?", "Hvad ville vi se?", "Hvornår er der forskel?"], skaerpelse: ["Hvem betaler prisen?", "Hvad med tilliden?", "Hvornår beskytter vi os selv?"], perspektiv: ["Hvad ville ændre sig?", "Hvad siger I nu?", "Hvad tager du ansvar for?"], erkendelse: "Mod til virkeligheden." },
    { label: "Det menneskelige rum", forside: "Hvad kræver det at holde fast?", aabning: ["Hvad er det sværeste?", "Hvad har du brug for?", "Hvornår er tvivl okay?"], skaerpelse: ["Hvad sker der med mennesker?", "Hvornår presser vi?", "Hvad koster manglende plads?"], perspektiv: ["Hvad giver energi?", "Hvad tager du med?", "Hvad gør du for dig selv?"], erkendelse: "Hvad forandring kræver." },
  ],
};

export function getKortForStep(step, rolle) {
  if (step.type === "aabning") return AABNING;
  if (step.type === "afslutning") return AFSLUTNING;
  const idx = step.nr - 1;
  if (step.type === "model") return MODEL_KORT[rolle]?.[idx];
  if (step.type === "human") return HUMAN_KORT[rolle]?.[idx];
  return null;
}
